language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install --prefer-source

script:
  - vendor/bin/atoum -d tests/units
